Repository aio-libs/multidict, pull requests merged in 2022-12, with the labels that each got.

#782 Replace version 3.11-dev by 3.11 in CI
  .github/workflows/ci.yml
  CHANGES/872.feature.rst
  setup.py
Labels: bot:chronographer:provided

#796 Fix linter stage of CI: replace libenchant-dev with libenchant-2-dev
  .github/workflows/ci.yml
Labels: bot:chronographer:skip

#794 Fix typo in multidict.rst
  docs/multidict.rst
Labels: bot:chronographer:skip

#798 Revert collections import
  .github/workflows/ci.yml
  CHANGES/798.bugfix
  Makefile
  multidict/__init__.pyi
  setup.cfg
Labels: bug, bot:chronographer:provided
