Repository aio-libs/multidict, pull requests merged in 2024-01, with the labels that each got.

#911 Fix the Towncrier philosophy link
  CHANGES/911.doc.rst
  CHANGES/README.rst
Labels: bot:chronographer:provided

#917 💅 Format typing & python modules
  multidict/__init__.pyi
  multidict/_multidict_py.py
Labels: bot:chronographer:skip

#918 🧪💅 Deduplicate MyPy config
  setup.cfg
Labels: enhancement, bot:chronographer:skip

#919 🧪 Migrate the MyPy invocation to pre-commit tool
  .pre-commit-config.yaml
  Makefile
  requirements/lint.txt
Labels: enhancement, bot:chronographer:skip

#916 🧪 Drop the explicit `__init__.py` from `tests/`
  .mypy.ini
  .pre-commit-config.yaml
  tests/__init__.py
Labels: enhancement, bot:chronographer:skip

#915 🧪 Rewire pytest fixtures avoiding import loops
  .github/workflows/ci-cd.yml
  .mypy.ini
  CHANGES/837.contrib.rst
  CHANGES/915.contrib.rst
  tests/cimultidict-c-extension.pickle.0
  tests/cimultidict-c-extension.pickle.1
  tests/cimultidict-c-extension.pickle.2
  tests/cimultidict-c-extension.pickle.3
  tests/cimultidict-c-extension.pickle.4
  tests/cimultidict-c-extension.pickle.5
  tests/cimultidict-pure-python.pickle.0
  tests/cimultidict-pure-python.pickle.1
  tests/cimultidict-pure-python.pickle.2
  tests/cimultidict-pure-python.pickle.3
  tests/cimultidict-pure-python.pickle.4
  tests/cimultidict-pure-python.pickle.5
  tests/conftest.py
  tests/gen_pickles.py
  tests/multidict-c-extension.pickle.0
  tests/multidict-c-extension.pickle.1
  tests/multidict-c-extension.pickle.2
  tests/multidict-c-extension.pickle.3
  tests/multidict-c-extension.pickle.4
  tests/multidict-c-extension.pickle.5
  tests/multidict-pure-python.pickle.0
  tests/multidict-pure-python.pickle.1
  tests/multidict-pure-python.pickle.2
  tests/multidict-pure-python.pickle.3
  tests/multidict-pure-python.pickle.4
  tests/multidict-pure-python.pickle.5
  tests/test_abc.py
  tests/test_copy.py
  tests/test_guard.py
  tests/test_istr.py
  tests/test_multidict.py
  tests/test_mutable_multidict.py
  tests/test_mypy.py
  tests/test_pickle.py
  tests/test_types.py
  tests/test_update.py
  tests/test_version.py
Labels: bug, enhancement, bot:chronographer:provided

#920 🧪 Run tests against Python 3.13 in CI
  .github/workflows/ci-cd.yml
  CHANGES/920.contrib.rst
Labels: bot:chronographer:provided

#909 Revert to using `PyArg_ParseTupleAndKeywords` under Python 3.13
  CHANGES/862.bugfix.1.rst
  CHANGES/909.bugfix.rst
  multidict/_multidict.c
Labels: bot:chronographer:provided

#927 Fix `MultiDict.items().isdisjoint()` for C Extensions
  CHANGES/927.bugfix.rst
  multidict/_multilib/views.h
  tests/test_multidict.py
Labels: bot:chronographer:provided
